### ISSUE TITLE
UDP scanning requires cap_net_raw priv

### ISSUE THREAD

**Issue by zenfish** [m57/piescan#3]
Raw sockets generally require root or CAP_NET_RAW capability.  There was a similar q on scapy here - 

https://stackoverflow.com/questions/22421290/scapy-operation-not-permitted-when-sending-packets

Perhaps a note in the README that says you need elevation... at the least you should put an exception in, or you get something like:

```
./piescan.py -sU -t 192.168.0.23 -p 623

	  piescan v1.1 -- https://www.twitter.com/@_g0dmode
	---------------------------------------------------
        ip_and_port = q.get()
	    A simple, fast, lightweight TCP/UDP scanner

[ 10:32:29 - 18/06/2019 ] Scan started - Host: 192.168.0.23

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./piescan.py", line 273, in sniffer_thread
    sniffer = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_ICMP)
  File "/usr/local/Cellar/python@2/2.7.15_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 1] Operation not permitted
```

**Comment by m57** [comment]
Yeah thats right, happy to take a pull request dude.

**Comment by m57** [comment]
done.
